name: Lint and test

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run docker containers
        run: docker-compose up -d

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn run lint

      - name: Run test
        run: yarn run test --coverage --verbose

      - name: Send coverage
        run: bash <(curl -s https://codecov.io/bash)
